site_name: Euclidean Norm
site_url: https://azmi-84.github.io/Euclidean-Norm/
repo_url: https://github.com/Azmi-84/Euclidean-Norm
edit_uri: edit/master/docs/

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

nav:
  - Home: index.md
  - About Me: about-me.md
  - Python Fundamental Course:
      - Module 01 - Python Basics:
          - Tokens and Basics: python_fundamental_course/modules/module_01/01_tokens_and_basics.ipynb
          - Data Types and Conversion: python_fundamental_course/modules/module_01/02_data_types_and_conversion.ipynb
      - Module 02 - Operators:
          - Operators and Expressions: python_fundamental_course/modules/module_02/01_operators_and_expressions.ipynb
      - Module 03 - Lists:
          - Lists and Indexing: python_fundamental_course/modules/module_03/01_lists_and_indexing.ipynb
      - Module 04 - Practice:
          - Data Types Problems and Practice: python_fundamental_course/modules/module_04/01_data_types_problems_practice.ipynb
      - Module 05 - Data Structures:
          - Tuples: python_fundamental_course/modules/module_05/01_tuples.ipynb
          - Sets: python_fundamental_course/modules/module_05/02_sets.ipynb
          - Dictionaries: python_fundamental_course/modules/module_05/03_dictionaries.ipynb
      - Module 06 - Functions:
          - Functions Basics: python_fundamental_course/modules/module_06/01_functions_basics.ipynb
          - Return Statements: python_fundamental_course/modules/module_06/02_return_statements.ipynb
          - Iterators and Generators: python_fundamental_course/modules/module_06/03_iterators_and_generators.ipynb
          - Lambda Functions: python_fundamental_course/modules/module_06/04_lambda_functions.ipynb
          - Map Function: python_fundamental_course/modules/module_06/05_map_function.ipynb
          - Filter Function: python_fundamental_course/modules/module_06/06_filter_function.ipynb
          - Reduce Function: python_fundamental_course/modules/module_06/07_reduce_function.ipynb
      - Module 07 - File Handling and Exceptions:
          - File Reading: python_fundamental_course/modules/module_07/01_file_reading.ipynb
          - File Writing: python_fundamental_course/modules/module_07/02_file_writing.ipynb
          - Exception Handling: python_fundamental_course/modules/module_07/03_exception_handling.ipynb
      - Module 08 - Object-Oriented Programming:
          - OOP Introduction: python_fundamental_course/modules/module_08/01_oop_introduction.ipynb
          - Inheritance: python_fundamental_course/modules/module_08/02_inheritance.ipynb
          - Polymorphism: python_fundamental_course/modules/module_08/03_polymorphism.ipynb
          - Abstraction: python_fundamental_course/modules/module_08/04_abstraction.ipynb
          - Encapsulation: python_fundamental_course/modules/module_08/05_encapsulation.ipynb
      - Module 09 - Advanced OOP:
          - Class Methods: python_fundamental_course/modules/module_09/01_class_methods.ipynb
      - Module 10 - NumPy Fundamentals:
          - NumPy Basics: python_fundamental_course/modules/module_10/01_numpy_basics.ipynb
      - Module 11 - NumPy Advanced:
          - NumPy Advanced Part 1: python_fundamental_course/modules/module_11/01_numpy_advanced_1.ipynb
          - NumPy Advanced Part 2: python_fundamental_course/modules/module_11/02_numpy_advanced_2.ipynb
          - NumPy Advanced Part 3: python_fundamental_course/modules/module_11/03_numpy_advanced_3.ipynb
      - Module 12 - Pandas Fundamentals:
          - Pandas Basics: python_fundamental_course/modules/module_12/01_pandas_basics.ipynb
          - Pandas DataFrames: python_fundamental_course/modules/module_12/02_pandas_dataframes.ipynb
      - Module 13 - Pandas Data Analysis:
          - Data Manipulation Part 1: python_fundamental_course/modules/module_13/01_pandas_manipulation_1.ipynb
          - Data Manipulation Part 2: python_fundamental_course/modules/module_13/02_pandas_manipulation_2.ipynb
          - Data Manipulation Part 3: python_fundamental_course/modules/module_13/03_pandas_manipulation_3.ipynb
          - Data Analysis Part 1: python_fundamental_course/modules/module_13/04_pandas_analysis_1.ipynb
          - Data Analysis Part 2: python_fundamental_course/modules/module_13/05_pandas_analysis_2.ipynb
      - Module 14 - Data Visualization with Matplotlib:
          - Matplotlib Basics: python_fundamental_course/modules/module_14/01_matplotlib_basics.ipynb
          - Matplotlib Advanced: python_fundamental_course/modules/module_14/02_matplotlib_advanced.ipynb
      - Module 15 - Interactive Visualizations:
          - Seaborn Visualizations: python_fundamental_course/modules/module_15/01_seaborn_visualizations.ipynb
          - Plotly Interactive Charts: python_fundamental_course/modules/module_15/02_plotly_interactive.ipynb
#  - Machine Learning Course: machine_learning_course/adaptive_boosting/adaptive_boosting_classifier.ipynb